server.port=${PORT:8080}

# Cấu hình kết nối trực tiếp biến môi trường từ Railway bằng tiền tố jdbc:
spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate và JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Ngăn ứng dụng bị sập ngay lập tức nếu database khởi động mất vài giây
spring.datasource.hikari.initialization-fail-timeout=-1