# 1. Cổng chạy trang web
server.port=${PORT:8080}

# 2. Tự động lấy URL của Railway, nếu không có (chạy ở máy phụ) thì dùng IP máy chính
spring.datasource.url=${MYSQL_URL:jdbc:mysql://192.168.1.68:3306/phongkham?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update